import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';

/**
 * Set up a pre-commit hook that runs viberails check on staged files.
 * Detects Lefthook, Husky, or falls back to a raw git hook.
 */
export function setupPreCommitHook(projectRoot: string): void {
  // Check for Lefthook
  const lefthookPath = path.join(projectRoot, 'lefthook.yml');
  if (fs.existsSync(lefthookPath)) {
    addLefthookPreCommit(lefthookPath);
    console.log(`  ${chalk.green('✓')} lefthook.yml — added viberails pre-commit`);
    return;
  }

  // Check for Husky
  const huskyDir = path.join(projectRoot, '.husky');
  if (fs.existsSync(huskyDir)) {
    writeHuskyPreCommit(huskyDir);
    console.log(`  ${chalk.green('✓')} .husky/pre-commit — added viberails check`);
    return;
  }

  // Fall back to raw git hook
  const gitDir = path.join(projectRoot, '.git');
  if (fs.existsSync(gitDir)) {
    const hooksDir = path.join(gitDir, 'hooks');
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }
    writeGitHookPreCommit(hooksDir);
    console.log(`  ${chalk.green('✓')} .git/hooks/pre-commit`);
  }
}

function writeGitHookPreCommit(hooksDir: string): void {
  const hookPath = path.join(hooksDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (existing.includes('viberails')) return;
    fs.writeFileSync(
      hookPath,
      `${existing.trimEnd()}\n\n# viberails check\nnpx viberails check --staged\n`,
    );
    return;
  }
  const script = [
    '#!/bin/sh',
    '# Generated by viberails — https://viberails.sh',
    '',
    'npx viberails check --staged',
    '',
  ].join('\n');
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
}

function addLefthookPreCommit(lefthookPath: string): void {
  const content = fs.readFileSync(lefthookPath, 'utf-8');
  if (content.includes('viberails')) return;

  const hasPreCommit = /^pre-commit:/m.test(content);
  if (hasPreCommit) {
    // Append under existing pre-commit section. This appends at the end of the file,
    // which works when pre-commit is the last section. A full YAML parser would handle
    // arbitrary section ordering, but we avoid that dependency to stay lightweight.
    const commandBlock = ['', '    viberails:', '      run: npx viberails check --staged'].join(
      '\n',
    );
    const updated = `${content.trimEnd()}\n${commandBlock}\n`;
    fs.writeFileSync(lefthookPath, updated);
  } else {
    // Add new pre-commit section
    const section = [
      '',
      'pre-commit:',
      '  commands:',
      '    viberails:',
      '      run: npx viberails check --staged',
    ].join('\n');
    fs.writeFileSync(lefthookPath, `${content.trimEnd()}\n${section}\n`);
  }
}

/**
 * Detect which pre-commit hook manager is present.
 * Returns a label like "Lefthook", "Husky", "git hook", or undefined if no .git.
 */
export function detectHookManager(projectRoot: string): string | undefined {
  if (fs.existsSync(path.join(projectRoot, 'lefthook.yml'))) return 'Lefthook';
  if (fs.existsSync(path.join(projectRoot, '.husky'))) return 'Husky';
  if (fs.existsSync(path.join(projectRoot, '.git'))) return 'git hook';
  return undefined;
}

/**
 * Set up a Claude Code PostToolUse hook that checks files after edit/write.
 * Writes to .claude/settings.json (project-level, team-shared).
 */
export function setupClaudeCodeHook(projectRoot: string): void {
  const claudeDir = path.join(projectRoot, '.claude');
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }

  const settingsPath = path.join(claudeDir, 'settings.json');
  let settings: Record<string, unknown> = {};

  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    } catch {
      console.warn(
        `  ${chalk.yellow('!')} .claude/settings.json contains invalid JSON — resetting to add hook`,
      );
      settings = {};
    }
  }

  const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;

  // Check if viberails hook already exists
  const existing = hooks.PostToolUse ?? [];
  if (existing.some((h) => JSON.stringify(h).includes('viberails'))) return;

  // The hook command reads the tool input from stdin, extracts file_path, and checks it.
  // Uses Node.js to parse JSON (no external dependency like jq required).
  // readFileSync(0) reads stdin synchronously via file descriptor 0.
  // `; exit 0` ensures warn-mode (always exit 0) while still showing check output.
  const extractFile =
    "node -e \"try{process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).tool_input?.file_path??'')}catch{}\"";
  const hookCommand = `FILE=$(${extractFile}) && [ -n "$FILE" ] && npx viberails check --files "$FILE" --format json; exit 0`;

  hooks.PostToolUse = [
    ...existing,
    {
      matcher: 'Edit|Write',
      hooks: [
        {
          type: 'command',
          command: hookCommand,
        },
      ],
    },
  ];

  settings.hooks = hooks;
  fs.writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  console.log(`  ${chalk.green('✓')} .claude/settings.json — added viberails PostToolUse hook`);
}

function writeHuskyPreCommit(huskyDir: string): void {
  const hookPath = path.join(huskyDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (!existing.includes('viberails')) {
      fs.writeFileSync(hookPath, `${existing.trimEnd()}\nnpx viberails check --staged\n`);
    }
    return;
  }
  fs.writeFileSync(hookPath, '#!/bin/sh\nnpx viberails check --staged\n', { mode: 0o755 });
}
