import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';

/**
 * Set up a pre-commit hook that runs viberails check on staged files.
 * Detects Lefthook, Husky, or falls back to a raw git hook.
 */
export function setupPreCommitHook(projectRoot: string): void {
  // Check for Lefthook
  const lefthookPath = path.join(projectRoot, 'lefthook.yml');
  if (fs.existsSync(lefthookPath)) {
    addLefthookPreCommit(lefthookPath);
    console.log(`  ${chalk.green('✓')} lefthook.yml — added viberails pre-commit`);
    return;
  }

  // Check for Husky
  const huskyDir = path.join(projectRoot, '.husky');
  if (fs.existsSync(huskyDir)) {
    writeHuskyPreCommit(huskyDir);
    console.log(`  ${chalk.green('✓')} .husky/pre-commit — added viberails check`);
    return;
  }

  // Fall back to raw git hook
  const gitDir = path.join(projectRoot, '.git');
  if (fs.existsSync(gitDir)) {
    const hooksDir = path.join(gitDir, 'hooks');
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }
    writeGitHookPreCommit(hooksDir);
    console.log(`  ${chalk.green('✓')} .git/hooks/pre-commit`);
  }
}

function writeGitHookPreCommit(hooksDir: string): void {
  const hookPath = path.join(hooksDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (existing.includes('viberails')) return;
    fs.writeFileSync(
      hookPath,
      `${existing.trimEnd()}\n\n# viberails check\nnpx viberails check --staged\n`,
    );
    return;
  }
  const script = [
    '#!/bin/sh',
    '# Generated by viberails — https://viberails.sh',
    '',
    'npx viberails check --staged',
    '',
  ].join('\n');
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
}

function addLefthookPreCommit(lefthookPath: string): void {
  const content = fs.readFileSync(lefthookPath, 'utf-8');
  if (content.includes('viberails')) return;
  const addition = ['', '  viberails:', '    run: npx viberails check --staged'].join('\n');
  fs.writeFileSync(lefthookPath, `${content.trimEnd()}\n${addition}\n`);
}

function writeHuskyPreCommit(huskyDir: string): void {
  const hookPath = path.join(huskyDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (!existing.includes('viberails')) {
      fs.writeFileSync(hookPath, `${existing.trimEnd()}\nnpx viberails check --staged\n`);
    }
    return;
  }
  fs.writeFileSync(hookPath, '#!/bin/sh\nnpx viberails check --staged\n', { mode: 0o755 });
}
