import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { IntegrationChoice } from '../utils/prompt-integrations.js';
import {
  setupClaudeCodeHook,
  setupClaudeMdReference,
  setupGithubAction,
  setupPreCommitHook,
} from './init-hooks.js';
import { resolveTypecheckCommand } from './resolve-typecheck.js';

/**
 * Add a named pre-commit command to the detected hook manager.
 * Idempotent — skips if the marker string is already present.
 */
export function addPreCommitStep(
  projectRoot: string,
  name: string,
  command: string,
  marker: string,
  lefthookExtra?: Record<string, string>,
): string | undefined {
  const lefthookPath = path.join(projectRoot, 'lefthook.yml');
  if (fs.existsSync(lefthookPath)) {
    const content = fs.readFileSync(lefthookPath, 'utf-8');
    if (content.includes(marker)) return undefined;
    const doc = parseYaml(content) ?? {};
    if (!doc['pre-commit']) doc['pre-commit'] = { commands: {} };
    if (!doc['pre-commit'].commands) doc['pre-commit'].commands = {};
    doc['pre-commit'].commands[name] = { run: command, ...lefthookExtra };
    fs.writeFileSync(lefthookPath, stringifyYaml(doc));
    return 'lefthook.yml';
  }

  const huskyDir = path.join(projectRoot, '.husky');
  if (fs.existsSync(huskyDir)) {
    const hookPath = path.join(huskyDir, 'pre-commit');
    if (fs.existsSync(hookPath)) {
      const existing = fs.readFileSync(hookPath, 'utf-8');
      if (existing.includes(marker)) return undefined;
      fs.writeFileSync(hookPath, `${existing.trimEnd()}\n${command}\n`);
    } else {
      fs.writeFileSync(hookPath, `#!/bin/sh\n${command}\n`, { mode: 0o755 });
    }
    return '.husky/pre-commit';
  }

  const gitDir = path.join(projectRoot, '.git');
  if (fs.existsSync(gitDir)) {
    const hooksDir = path.join(gitDir, 'hooks');
    if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir, { recursive: true });
    const hookPath = path.join(hooksDir, 'pre-commit');
    if (fs.existsSync(hookPath)) {
      const existing = fs.readFileSync(hookPath, 'utf-8');
      if (existing.includes(marker)) return undefined;
      fs.writeFileSync(hookPath, `${existing.trimEnd()}\n\n# ${name}\n${command}\n`);
    } else {
      fs.writeFileSync(hookPath, `#!/bin/sh\n# Generated by viberails\n\n# ${name}\n${command}\n`, {
        mode: 0o755,
      });
    }
    return '.git/hooks/pre-commit';
  }

  return undefined;
}

/** Set up a typecheck pre-commit step. Skips if no safe command can be inferred. */
export function setupTypecheckHook(
  projectRoot: string,
  packageManager?: string,
): string | undefined {
  const resolved = resolveTypecheckCommand(projectRoot, packageManager);
  if (!resolved.command) {
    console.log(`  ${chalk.yellow('!')} Skipped typecheck hook: ${resolved.reason}`);
    return undefined;
  }
  const target = addPreCommitStep(projectRoot, 'typecheck', resolved.command, 'typecheck');
  if (target) {
    console.log(`  ${chalk.green('✓')} ${target} — added typecheck (${resolved.label})`);
  }
  return target;
}

/** Set up a linter pre-commit step scoped to staged files. */
export function setupLintHook(projectRoot: string, linter: string): string | undefined {
  const isLefthook = fs.existsSync(path.join(projectRoot, 'lefthook.yml'));
  const linterName = linter === 'biome' ? 'Biome' : 'ESLint';

  let command: string;
  let lefthookExtra: Record<string, string> | undefined;

  if (isLefthook) {
    command = linter === 'biome' ? 'npx biome check {staged_files}' : 'npx eslint {staged_files}';
    lefthookExtra = {
      glob: linter === 'biome' ? '*.{js,ts,jsx,tsx,json,css}' : '*.{js,ts,jsx,tsx}',
    };
  } else {
    const exts =
      linter === 'biome'
        ? "'*.js' '*.ts' '*.jsx' '*.tsx' '*.json' '*.css'"
        : "'*.js' '*.ts' '*.jsx' '*.tsx'";
    const lintCmd = linter === 'biome' ? 'biome check' : 'eslint';
    command = `git diff --cached --name-only --diff-filter=ACMR -- ${exts} | xargs npx ${lintCmd}`;
  }

  const target = addPreCommitStep(projectRoot, 'lint', command, linter, lefthookExtra);
  if (target) {
    console.log(`  ${chalk.green('✓')} ${target} — added ${linterName} lint check`);
  }
  return target;
}

/** Apply selected integrations and return list of created file descriptions. */
export function setupSelectedIntegrations(
  projectRoot: string,
  integrations: IntegrationChoice,
  opts: { linter?: string; packageManager?: string },
): string[] {
  const created: string[] = [];
  if (integrations.preCommitHook) {
    const t = setupPreCommitHook(projectRoot);
    created.push(t ? `${t} — added viberails pre-commit` : 'pre-commit hook skipped');
  }
  if (integrations.typecheckHook) {
    const t = setupTypecheckHook(projectRoot, opts.packageManager);
    if (t) created.push(`${t} — added typecheck`);
  }
  if (integrations.lintHook && opts.linter) {
    const t = setupLintHook(projectRoot, opts.linter);
    if (t) created.push(`${t} — added lint check`);
  }
  if (integrations.claudeCodeHook) {
    setupClaudeCodeHook(projectRoot);
    created.push('.claude/settings.json — added viberails hook');
  }
  if (integrations.claudeMdRef) {
    setupClaudeMdReference(projectRoot);
    created.push('CLAUDE.md — added @.viberails/context.md reference');
  }
  if (integrations.githubAction) {
    const t = setupGithubAction(projectRoot, opts.packageManager ?? 'npm', {
      linter: integrations.lintHook ? opts.linter : undefined,
      typecheck: integrations.typecheckHook,
    });
    if (t) created.push(`${t} — blocks PRs on violations`);
  }
  return created;
}
