import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

/**
 * Set up a pre-commit hook that runs viberails check on staged files.
 * Detects Lefthook, Husky, or falls back to a raw git hook.
 */
export function setupPreCommitHook(projectRoot: string): string | undefined {
  // Check for Lefthook
  const lefthookPath = path.join(projectRoot, 'lefthook.yml');
  if (fs.existsSync(lefthookPath)) {
    addLefthookPreCommit(lefthookPath);
    console.log(`  ${chalk.green('✓')} lefthook.yml — added viberails pre-commit`);
    return 'lefthook.yml';
  }

  // Check for Husky
  const huskyDir = path.join(projectRoot, '.husky');
  if (fs.existsSync(huskyDir)) {
    writeHuskyPreCommit(huskyDir);
    console.log(`  ${chalk.green('✓')} .husky/pre-commit — added viberails check`);
    return '.husky/pre-commit';
  }

  // Fall back to raw git hook
  const gitDir = path.join(projectRoot, '.git');
  if (fs.existsSync(gitDir)) {
    const hooksDir = path.join(gitDir, 'hooks');
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }
    writeGitHookPreCommit(hooksDir);
    console.log(`  ${chalk.green('✓')} .git/hooks/pre-commit`);
    return '.git/hooks/pre-commit';
  }

  return undefined;
}

function writeGitHookPreCommit(hooksDir: string): void {
  const hookPath = path.join(hooksDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (existing.includes('viberails')) return;
    fs.writeFileSync(
      hookPath,
      `${existing.trimEnd()}\n\n# viberails check\nnpx viberails check --staged\n`,
    );
    return;
  }
  const script = [
    '#!/bin/sh',
    '# Generated by viberails — https://viberails.sh',
    '',
    'npx viberails check --staged',
    '',
  ].join('\n');
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
}

function addLefthookPreCommit(lefthookPath: string): void {
  const content = fs.readFileSync(lefthookPath, 'utf-8');
  if (content.includes('viberails')) return;

  const doc = parseYaml(content) ?? {};

  if (!doc['pre-commit']) {
    doc['pre-commit'] = { commands: {} };
  }
  if (!doc['pre-commit'].commands) {
    doc['pre-commit'].commands = {};
  }

  doc['pre-commit'].commands.viberails = {
    run: 'npx viberails check --staged',
  };

  fs.writeFileSync(lefthookPath, stringifyYaml(doc));
}

/**
 * Detect which pre-commit hook manager is present.
 * Returns a label like "Lefthook", "Husky", "git hook", or undefined if no .git.
 */
export function detectHookManager(projectRoot: string): string | undefined {
  if (fs.existsSync(path.join(projectRoot, 'lefthook.yml'))) return 'Lefthook';
  if (fs.existsSync(path.join(projectRoot, '.husky'))) return 'Husky';
  if (fs.existsSync(path.join(projectRoot, '.git'))) return 'git hook';
  return undefined;
}

/**
 * Set up a Claude Code PostToolUse hook that checks files after edit/write.
 * Writes to .claude/settings.json (project-level, team-shared).
 */
export function setupClaudeCodeHook(projectRoot: string): void {
  const claudeDir = path.join(projectRoot, '.claude');
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }

  const settingsPath = path.join(claudeDir, 'settings.json');
  let settings: Record<string, unknown> = {};

  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    } catch {
      console.warn(
        `  ${chalk.yellow('!')} .claude/settings.json contains invalid JSON — skipping hook setup`,
      );
      console.warn(`  Fix the JSON manually, then re-run ${chalk.cyan('viberails init --force')}`);
      return;
    }
  }

  const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;

  // Check if viberails hook already exists
  const existing = hooks.PostToolUse ?? [];
  if (existing.some((h) => JSON.stringify(h).includes('viberails'))) return;

  // The --hook flag handles everything: reads stdin JSON, extracts file_path,
  // runs the check, outputs violations to stderr, and exits 2 on violations.
  // Prefer the local binary (fast) over npx (slow cold-start).
  const hookCommand =
    'if [ -x ./node_modules/.bin/viberails ]; then ./node_modules/.bin/viberails check --hook; else npx viberails check --hook; fi';

  hooks.PostToolUse = [
    ...existing,
    {
      matcher: 'Edit|Write',
      hooks: [
        {
          type: 'command',
          command: hookCommand,
        },
      ],
    },
  ];

  settings.hooks = hooks;
  fs.writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  console.log(`  ${chalk.green('✓')} .claude/settings.json — added viberails PostToolUse hook`);
}

/**
 * Append a @.viberails/context.md reference to the project's CLAUDE.md.
 * Creates CLAUDE.md if it doesn't exist. Skips if the reference is already present.
 */
export function setupClaudeMdReference(projectRoot: string): void {
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  let content = '';

  if (fs.existsSync(claudeMdPath)) {
    content = fs.readFileSync(claudeMdPath, 'utf-8');
  }

  if (content.includes('@.viberails/context.md')) return;

  const ref = '\n@.viberails/context.md\n';
  const prefix = content.length === 0 ? '' : content.trimEnd();
  fs.writeFileSync(claudeMdPath, prefix + ref);
  console.log(`  ${chalk.green('✓')} CLAUDE.md — added @.viberails/context.md reference`);
}

function writeHuskyPreCommit(huskyDir: string): void {
  const hookPath = path.join(huskyDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (!existing.includes('viberails')) {
      fs.writeFileSync(hookPath, `${existing.trimEnd()}\nnpx viberails check --staged\n`);
    }
    return;
  }
  fs.writeFileSync(hookPath, '#!/bin/sh\nnpx viberails check --staged\n', { mode: 0o755 });
}
