import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type { ScanResult, ViberailsConfig } from '@viberails/types';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { writeGeneratedFiles } from './write-generated-files.js';

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'write-gen-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

function makeConfig(): ViberailsConfig {
  return {
    version: 1,
    name: 'test',
    rules: {
      maxFileLines: 300,
      maxTestFileLines: 0,
      testCoverage: 80,
      enforceNaming: true,
      enforceBoundaries: false,
    },
    packages: [{ name: 'test', path: '.' }],
  };
}

function makeScanResult(): ScanResult {
  return {
    root: tmpDir,
    stack: {
      language: { name: 'typescript' },
      packageManager: { name: 'pnpm' },
      libraries: [],
    },
    structure: { directories: [] },
    conventions: {},
    statistics: {
      totalFiles: 1,
      totalLines: 10,
      averageFileLines: 10,
      largestFiles: [],
      filesByExtension: {},
    },
    packages: [],
  };
}

describe('writeGeneratedFiles', () => {
  it('creates .viberails directory and files', () => {
    writeGeneratedFiles(tmpDir, makeConfig(), makeScanResult());
    expect(fs.existsSync(path.join(tmpDir, '.viberails', 'context.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, '.viberails', 'scan-result.json'))).toBe(true);
  });

  it('writes valid JSON for scan-result.json', () => {
    writeGeneratedFiles(tmpDir, makeConfig(), makeScanResult());
    const content = fs.readFileSync(path.join(tmpDir, '.viberails', 'scan-result.json'), 'utf-8');
    expect(() => JSON.parse(content)).not.toThrow();
  });

  it('writes context.md with generated header', () => {
    writeGeneratedFiles(tmpDir, makeConfig(), makeScanResult());
    const content = fs.readFileSync(path.join(tmpDir, '.viberails', 'context.md'), 'utf-8');
    expect(content).toContain('Generated by viberails');
  });
});
