import type { ViberailsConfig } from '@viberails/types';
import {
  formatBoundaryRules,
  formatDevelopmentSetup,
  formatPackageOverrides,
  getRootPackage,
  NAMING_EXAMPLES,
} from './format-helpers.js';

/**
 * Build the list of enforced rules as markdown bullet points.
 */
function formatEnforcedRules(config: ViberailsConfig): string[] {
  const root = getRootPackage(config);
  const { rules } = config;
  const lines: string[] = [];

  if (rules.maxFileLines > 0) {
    lines.push(
      `- Files must not exceed **${rules.maxFileLines} lines**. Split into focused modules.`,
    );
  }

  if (rules.enforceNaming && root.conventions?.fileNaming) {
    const val = root.conventions.fileNaming;
    const examples = NAMING_EXAMPLES[val] ?? `e.g. \`my-module.ts\``;
    lines.push(`- Source files use **${val}**: ${examples}.`);
  }

  const enforceMissing = rules.enforceMissingTests ?? rules.testCoverage > 0;
  if (enforceMissing && root.structure?.testPattern) {
    if (root.structure.srcDir) {
      lines.push(
        `- Every source file in \`${root.structure.srcDir}/\` must have a corresponding \`${root.structure.testPattern}\` file.`,
      );
    } else {
      lines.push(
        `- Every source file must have a corresponding \`${root.structure.testPattern}\` file.`,
      );
    }
  }

  if (rules.testCoverage > 0) {
    lines.push(`- Test line coverage must meet **${rules.testCoverage}%** threshold.`);
  }

  return lines;
}

/**
 * Generate a rules-focused context document from a ViberailsConfig.
 *
 * The output tells AI agents what rules are enforced and that commits
 * will fail if they are violated. It does not describe the project's
 * stack, structure, or architecture — that is trivially discoverable.
 *
 * @param config - The viberails configuration
 * @returns Markdown string for `.viberails/context.md`
 */
export function generateContext(config: ViberailsConfig): string {
  const sections: string[] = [];

  sections.push(
    "<!-- Generated by viberails. Do not edit — re-run 'viberails sync' to update. -->\n",
  );
  sections.push('# viberails enforced rules\n');

  sections.push(
    'These rules are checked by viberails. Use `viberails check --enforce` to block commits on violation:\n',
  );

  const setupLines = formatDevelopmentSetup(config);
  if (setupLines.length > 0) {
    sections.push(setupLines.join('\n'));
    sections.push('');
  }

  const ruleLines = formatEnforcedRules(config);
  if (ruleLines.length > 0) {
    sections.push(ruleLines.join('\n'));
  } else {
    sections.push('_(No rules configured. Edit `viberails.config.json` to add rules.)_');
  }

  const packageLines = formatPackageOverrides(config);
  if (packageLines.length > 0) {
    sections.push('');
    sections.push(packageLines.join('\n'));
  }

  const boundaryLines = formatBoundaryRules(config);
  if (boundaryLines.length > 0) {
    sections.push('');
    sections.push(boundaryLines.join('\n'));
  }

  sections.push('');

  return sections.join('\n');
}
