import type { ViberailsConfig } from '@viberails/types';
import {
  conventionValue,
  formatBoundaryRules,
  formatPackageOverrides,
  NAMING_EXAMPLES,
} from './format-helpers.js';

/**
 * Build the list of enforced rules as markdown bullet points.
 */
function formatEnforcedRules(config: ViberailsConfig): string[] {
  const { rules, conventions, structure } = config;
  const lines: string[] = [];

  if (rules.maxFileLines > 0) {
    lines.push(
      `- Files must not exceed **${rules.maxFileLines} lines**. Split into focused modules.`,
    );
  }

  if (rules.enforceNaming && conventions.fileNaming) {
    const val = conventionValue(conventions.fileNaming);
    const examples = NAMING_EXAMPLES[val] ?? `e.g. \`my-module.ts\``;
    lines.push(`- Source files use **${val}**: ${examples}.`);
  }

  if (rules.requireTests && structure.testPattern) {
    if (structure.srcDir) {
      lines.push(
        `- Every source file in \`${structure.srcDir}/\` must have a corresponding \`${structure.testPattern}\` file.`,
      );
    } else {
      lines.push(
        `- Every source file must have a corresponding \`${structure.testPattern}\` file.`,
      );
    }
  }

  return lines;
}

/**
 * Generate a rules-focused context document from a ViberailsConfig.
 *
 * The output tells AI agents what rules are enforced and that commits
 * will fail if they are violated. It does not describe the project's
 * stack, structure, or architecture — that is trivially discoverable.
 *
 * @param config - The viberails configuration
 * @returns Markdown string for `.viberails/context.md`
 */
export function generateContext(config: ViberailsConfig): string {
  const sections: string[] = [];

  sections.push(
    "<!-- Generated by viberails. Do not edit — re-run 'viberails sync' to update. -->\n",
  );
  sections.push('# viberails enforced rules\n');

  if (config.enforcement === 'enforce') {
    sections.push('Commits will be rejected if these rules are violated:\n');
  } else {
    sections.push(
      'These rules are checked before commits. Violations will be **warned** but not blocked:\n',
    );
  }

  const ruleLines = formatEnforcedRules(config);
  if (ruleLines.length > 0) {
    sections.push(ruleLines.join('\n'));
  } else {
    sections.push('_(No rules configured. Edit `viberails.config.json` to add rules.)_');
  }

  const packageLines = formatPackageOverrides(config);
  if (packageLines.length > 0) {
    sections.push('');
    sections.push(packageLines.join('\n'));
  }

  const boundaryLines = formatBoundaryRules(config);
  if (boundaryLines.length > 0) {
    sections.push('');
    sections.push(boundaryLines.join('\n'));
  }

  sections.push('');

  return sections.join('\n');
}
