import type { ViberailsConfig } from '@viberails/types';
import { describe, expect, it } from 'vitest';
import { generateContext } from './generate-context.js';

function makeConfig(overrides: Partial<ViberailsConfig> = {}): ViberailsConfig {
  return {
    version: 2,
    name: 'test-app',
    rules: {
      maxFileLines: 300,
      maxTestFileLines: 0,
      testCoverage: 80,
      enforceNaming: true,
      enforceBoundaries: false,
    },
    ignore: [],
    packages: [
      {
        name: 'test-app',
        path: '.',
        stack: { language: 'typescript', packageManager: 'pnpm' },
        structure: { srcDir: 'src', testPattern: '*.test.ts', tests: '__tests__' },
        conventions: {
          fileNaming: 'kebab-case',
        },
      },
    ],
    ...overrides,
  };
}

describe('generateContext (rules-focused)', () => {
  it('starts with auto-generated header comment', () => {
    const output = generateContext(makeConfig());
    expect(output).toMatch(
      /^<!-- Generated by viberails\. Do not edit — re-run 'viberails sync' to update\. -->/,
    );
  });

  it('contains the enforced rules heading', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('# viberails enforced rules');
  });

  it('mentions file size limit', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('300 lines');
  });

  it('does not mention function size limit (not enforced by check)', () => {
    const output = generateContext(makeConfig());
    expect(output).not.toContain('50 lines');
  });

  it('mentions naming convention with example', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('kebab-case');
    expect(output).toContain('user-profile.ts');
  });

  it('mentions test requirement', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('*.test.ts');
    expect(output).toContain('src/');
  });

  it('mentions viberails check --enforce for blocking commits', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('viberails check --enforce');
  });

  it('does not describe the project stack or architecture', () => {
    const output = generateContext(makeConfig());
    expect(output).not.toContain('## Architecture');
    expect(output).not.toContain('TypeScript');
    expect(output).not.toContain('pnpm');
  });

  it('does not include check command reminder', () => {
    const output = generateContext(makeConfig());
    expect(output).not.toContain('Run `viberails check`');
  });

  it('handles missing conventions gracefully', () => {
    const output = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: { srcDir: 'src', testPattern: '*.test.ts', tests: '__tests__' },
            conventions: {},
          },
        ],
      }),
    );
    expect(output).not.toContain('kebab-case');
    expect(output).toContain('300 lines');
  });

  it('shows no-rules message when all rules are disabled', () => {
    const output = generateContext(
      makeConfig({
        rules: {
          maxFileLines: 0,
          maxTestFileLines: 0,
          testCoverage: 0,
          enforceNaming: false,
          enforceBoundaries: false,
        },
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: {},
            conventions: {},
          },
        ],
      }),
    );
    expect(output).toContain('No rules configured');
  });

  it('handles string convention values', () => {
    const output = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: { srcDir: 'src', testPattern: '*.test.ts' },
            conventions: { fileNaming: 'camelCase' },
          },
        ],
      }),
    );
    expect(output).toContain('camelCase');
    expect(output).toContain('userProfile.ts');
  });

  it('includes boundary rules section when boundaries are configured', () => {
    const output = generateContext(
      makeConfig({
        rules: { ...makeConfig().rules, enforceBoundaries: true },
        boundaries: { deny: { '@app/ui': ['@app/api'] } },
      }),
    );
    expect(output).toContain('## Boundary rules');
    expect(output).toContain('`@app/ui` must NOT import from: `@app/api`');
  });

  it('omits boundary section when enforceBoundaries is false', () => {
    const output = generateContext(
      makeConfig({
        rules: { ...makeConfig().rules, enforceBoundaries: false },
        boundaries: { deny: { '@app/ui': ['@app/api'] } },
      }),
    );
    expect(output).not.toContain('Boundary rules');
  });

  it('omits boundary section when deny map is empty', () => {
    const output = generateContext(
      makeConfig({
        rules: { ...makeConfig().rules, enforceBoundaries: true },
        boundaries: { deny: {} },
      }),
    );
    expect(output).not.toContain('Boundary rules');
  });

  it('groups multiple denied targets on one line', () => {
    const output = generateContext(
      makeConfig({
        rules: { ...makeConfig().rules, enforceBoundaries: true },
        boundaries: { deny: { components: ['pages', 'api'] } },
      }),
    );
    expect(output).toContain('`components` must NOT import from: `pages`, `api`');
  });
});

describe('per-package rules', () => {
  it('omits per-package section when only root package', () => {
    const result = generateContext(makeConfig());
    expect(result).not.toContain('Per-package rules');
  });

  it('does not include per-package section when only root package exists', () => {
    const result = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: {},
            conventions: {},
          },
        ],
      }),
    );
    expect(result).not.toContain('Per-package rules');
  });

  it('includes per-package section with convention override', () => {
    const result = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: { srcDir: 'src', testPattern: '*.test.ts' },
            conventions: { fileNaming: 'kebab-case' },
          },
          {
            name: '@app/mobile',
            path: 'apps/mobile',
            stack: { framework: 'expo@53' },
            conventions: { fileNaming: 'PascalCase' },
          },
        ],
      }),
    );
    expect(result).toContain('## Per-package rules');
    expect(result).toContain('### apps/mobile (expo)');
    expect(result).toContain('**PascalCase**');
  });

  it('shows package header without framework when stack is absent', () => {
    const result = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: { srcDir: 'src', testPattern: '*.test.ts' },
            conventions: { fileNaming: 'kebab-case' },
          },
          {
            name: '@app/shared',
            path: 'packages/shared',
            conventions: { fileNaming: 'camelCase' },
          },
        ],
      }),
    );
    expect(result).toContain('### packages/shared');
    expect(result).not.toContain('(');
  });

  it('includes rule overrides for maxFileLines', () => {
    const result = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: {},
            conventions: {},
          },
          {
            name: '@app/web',
            path: 'apps/web',
            rules: { maxFileLines: 200 },
          },
        ],
      }),
    );
    expect(result).toContain('**200 lines**');
  });

  it('includes all convention overrides, not just fileNaming', () => {
    const result = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: {},
            conventions: {},
          },
          {
            name: '@app/mobile',
            path: 'apps/mobile',
            conventions: {
              fileNaming: 'PascalCase',
              componentNaming: 'PascalCase',
              hookNaming: 'useXxx',
              importAlias: '~/*',
            },
          },
        ],
      }),
    );
    expect(result).toContain('**PascalCase**');
    expect(result).toContain('Components use **PascalCase** naming');
    expect(result).toContain('Hooks use **useXxx** naming');
    expect(result).toContain('Import alias: `~/*`');
  });
});

describe('development setup section', () => {
  it('does not include development setup section', () => {
    const output = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: {
              language: 'typescript',
              packageManager: 'pnpm',
              formatter: 'biome@2',
              linter: 'biome@2',
            },
            structure: {},
            conventions: {},
          },
        ],
      }),
    );
    expect(output).not.toContain('## Development setup');
  });
});

describe('flat project handling', () => {
  it('omits srcDir from test requirement when project has no srcDir', () => {
    const output = generateContext(
      makeConfig({
        packages: [
          {
            name: 'test-app',
            path: '.',
            stack: { language: 'typescript', packageManager: 'pnpm' },
            structure: { testPattern: '*.test.ts' },
            conventions: { fileNaming: 'kebab-case' },
          },
        ],
      }),
    );
    expect(output).toContain('Every source file must have a corresponding');
    expect(output).not.toContain('src/');
  });

  it('includes srcDir in test requirement when present', () => {
    const output = generateContext(makeConfig());
    expect(output).toContain('src/');
  });
});
